spring.application.name=StockQueryService
server.port=8003
spring.datasource.url=${JDBC_DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${JDBC_DATABASE_USERNAME}
spring.datasource.password=${JDBC_DATABASE_PASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
SECRET_KEY=${SECRET_KEY_ENV}
eureka.client.service-url.defaultZone= ${EUREKA_URL}
eureka.instance.prefer-ip-address=true
security.jwt.secret=${SECURITY_JWT_SECRET}

# Kafka
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=stock-op
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer



logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG